[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"

[build.environment]
  NODE_VERSION = "18.16.0"

[[plugins]]
  package = "@netlify/next"

[[redirects]]
  from = "/api/*"
  to = "https://video-caption-generator-ggad.onrender.com/api/:splat"
  status = 200
  force = true
